# Generated by Django 5.0 on 2023-12-06 22:10

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_activity_file_task_file_alter_process_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Renk'),
        ),
    ]
